services:
  mysql:
    image: mysql:8.0
    container_name: VanGo-DB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - vango

  backend:
    build: ./VanGo-Back
    container_name: VanGo-backend
    restart: always
    depends_on:
      - mysql
      - minio
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: bucket-vango
    ports:
      - "8080:8080"
    networks:
      - vango

  frontend:
    build: ./VanGo-Front
    container_name: VanGo-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "${FRONT_PORT}:80"
    networks:
      - vango

  minio:
    image: minio/minio:latest
    container_name: VanGo-minIO-blog
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - vango

  VanGo-minIO-client:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 30 &&
      mc alias set local http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY} &&
      mc mb --ignore-existing local/bucket-vango &&
      mc policy set public local/bucket-vango
      "
    networks:
        - vango

volumes:
  mysql_data:
  minio_data:

networks:
  vango:
